version: '0.1'
services:
  
  frontend:
    build:
      context: src/frontend/
      # for production, use the following
      # dockerfile: dockerfile.prod
      dockerfile: dockerfile
      args:
        - API_URL=http://localhost:5000
        - PORT=80
    ports:
      - "80:80"


  backend:
    build: 
      context: src/backend/
      args:
        - PORT=5000
    ports:
      - "5000:5000"